// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "4cbf63fa-dc62-4315-94b4-0b912cf5b1cf";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onPanelCurrentChange();

String trackingStatus;
float panelCurrent;
float panelVoltage;
int ldrLeft;
int ldrRight;
int servoAngle;
bool isStable;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(trackingStatus, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(panelCurrent, READWRITE, ON_CHANGE, onPanelCurrentChange);
  ArduinoCloud.addProperty(panelVoltage, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(ldrLeft, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(ldrRight, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(servoAngle, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(isStable, READ, ON_CHANGE, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
